print("Hi, what is your username?")
username = input()
print("How old are you?")
age = input()
print("What is you DOB?")
DOB = input()
print("What is your address?")
address = input()
print("What are your hobbies?")
hobbies = input()

print(f"Hi {username.capitalize()} you are {age} years old and your date of birth is {DOB}, you live at {address}, your hobbies are {hobbies}")